# -*- coding: utf-8 -*-
"""Movies .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeRhQPLbP_QfQE6-zAj5_YGBJEG_GGP9

**STAGE** **1**

Data Preparation
"""

# Import Libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from scipy.stats import ttest_ind, chi2_contingency

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report
)

import joblib

sns.set_style("whitegrid")

"""Load Dataset"""

# Load Dataset
from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("movies.csv")

df = pd.read_csv("movies.csv")
print(df.columns)

"""Dataset First Look

"""

# Display First 5 Rows

df.head()

# Display Last 5 Rows

df.tail()

print(df.columns.tolist())

df = ['genres']

"""Dataset Rows & Columns Count"""

df = pd.read_csv("movies.csv")
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

"""Dataset Information"""

df.info()

"""Dataset Columns"""

df.columns

"""Dataset Statistics"""

df.describe()

"""Missing Values"""

df.isnull().sum()

"""Missing Value Percentage"""

(df.isnull().sum()/len(df))*100

"""Duplicate Values"""

df.duplicated().sum()

#Remove duplicates
df = df.drop_duplicates()

#Check again
df.duplicated().sum()

"""Check Budget = 0

"""

(df["budget"]==0).sum()

#Display rows
df[df["budget"]==0]

"""Remove Invalid Movies
Since a budget or revenue of 0 does not allow meaningful success prediction, remove those rows.
"""

df = df[(df["budget"]>0) & (df["revenue"]>0)]

#Check the new shape.

df.shape

"""**Create Target Variable**
Success is defined as:
Revenue > Budget → 1
Revenue ≤ Budget → 0
"""

df["success"] = np.where(df["revenue"]>df["budget"],1,0)

#Check the data.

df.head()

"""Success Distribution"""

df["success"].value_counts()

#Percentage

df["success"].value_counts(normalize=True)*100

"""Success Count Plot"""

plt.figure(figsize=(6,4))

sns.countplot(data=df,x="success")

plt.title("Success Distribution")
plt.xlabel("Success")
plt.ylabel("Count")

plt.show()

"""**Genre Cleaning**
Extract only the first genre name.
"""

import ast

def extract_genre(x):
    try:
        genres = ast.literal_eval(x)
        return genres[0]["name"] if len(genres)>0 else "Unknown"
    except:
        return "Unknown"

df["genre"] = df["genres"].apply(extract_genre)

#Check

df[["genres","genre"]].head()

"""Genre Counts"""

df["genres"].value_counts()

"""**STAGE 2**  Exploratory Data Analysis (EDA)

Budget vs Revenue Analysis

Step 1: Create Scatter Plot
"""

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x="budget",
    y="revenue",
    alpha=0.6
)

plt.title("Budget vs Revenue")
plt.xlabel("Budget")
plt.ylabel("Revenue")

plt.show()

"""EDA 2: Genre Analysis

This requirement has two parts.

Part A: Most Common Genres

Heading

Step 1

"""

genre_count = df["genre"].value_counts().head(10)
genre_count

"""Step 2"""

plt.figure(figsize=(10,6))

sns.barplot(
    x=genre_count.values,
    y=genre_count.index
)

plt.title("Top 10 Most Common Genres")
plt.xlabel("Number of Movies")
plt.ylabel("Genre")

plt.show()

"""Part B: Genre Success Rate

Step 1
"""

genre_success = df.groupby("genre")["success"].mean().sort_values(ascending=False)
genre_success

"""Step 2"""

plt.figure(figsize=(10,6))

sns.barplot(
    x=genre_success.values,
    y=genre_success.index
)

plt.title("Genre Success Rate")
plt.xlabel("Success Rate")
plt.ylabel("Genre")

plt.show()

"""EDA 3: Popularity, Runtime and Vote Average vs Success

The assignment asks you to compare these variables with the target (success).

Plot 1
Popularity vs Success
"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="success",
    y="popularity"
)

plt.title("Popularity vs Success")

plt.show()

"""Plot 2
Runtime vs Success
"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="success",
    y="runtime"
)

plt.title("Runtime vs Success")

plt.show()

"""Plot 3
Vote Average vs Success
"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="success",
    y="vote_average"
)

plt.title("Vote Average vs Success")

plt.show()

"""EDA 4: Correlation Heatmap

Heading

Step 1

Select numeric columns.
"""

numeric_df = df[
    [
        "budget",
        "revenue",
        "popularity",
        "runtime",
        "vote_average",
        "success"
    ]
]

"""Step 2

Correlation Matrix
"""

corr = numeric_df.corr()
corr

"""Step 3

Heatmap
"""

plt.figure(figsize=(8,6))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

"""STAGE 3: Statistical Testing

3.1 T-Test

Heading

Step 1: Import Library
"""

from scipy.stats import ttest_ind

"""Step 2: Separate the Data"""

success_movies = df[df["success"] == 1]["popularity"]

failure_movies = df[df["success"] == 0]["popularity"]

"""Step 3: Perform T-Test"""

t_stat, p_value = ttest_ind(
    success_movies,
    failure_movies,
    equal_var=False
)

print("T-Statistic :", t_stat)
print("P-value :", p_value)

"""Step 4: Decision"""

alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
else:
    print("Fail to Reject the Null Hypothesis")

"""**Step 5: Write the Hypothese**

**Null Hypothesis (H₀)**

There is no significant difference in movie popularity between successful and unsuccessful movies.

**Alternative Hypothesis (H₁)**

There is a significant difference in movie popularity between successful and unsuccessful movies.

**Step 6: Write the Conclusion**

***If p < 0.05***

Since the p-value is less than 0.05, we reject the null hypothesis. This indicates that popularity differs significantly between successful and unsuccessful movies.

**If p ≥ 0.05**

Since the p-value is greater than 0.05, we fail to reject the null hypothesis. This indicates that there is no statistically significant difference in popularity between successful and unsuccessful movies.

STAGE 4: Predictive Modeling (Random Forest)

4.1 Feature Selection

Heading

Step 1: Select Features and Target
"""

features = ["budget", "popularity", "runtime", "vote_average"]

X = df[features]

y = df["success"]

"""Step 2: Check Data"""

X.head()

y.head()

"""Explanation

Features Used

Budget
Popularity
Runtime
Vote Average

Excluded Columns

Revenue → Used to create the target variable (success), so including it would leak information.
Title → Text field that doesn't directly help the model.
Genres → Can be encoded later, but we'll keep the first model simple.

4.2 Train-Test Split

Heading

Split Data
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

"""Check Shapes"""

print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Target :", y_train.shape)
print("Testing Target :", y_test.shape)

"""Explanation

Use an 80:20 split.

80% → Training
20% → Testing

A separate test set helps evaluate how well the model performs on unseen data.

4.3 Train Random Forest Classifier

Heading

Train Model
"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    random_state=42
)

rf_model.fit(X_train, y_train)

"""Explanation

A Random Forest is an ensemble learning algorithm that builds many decision trees using different subsets of the training data and features. Each tree predicts whether a movie is successful or not, and the final prediction is determined by the majority vote of all trees.

4.4 Predictions

Heading

Predict
"""

y_pred = rf_model.predict(X_test)

"""View Predictions"""

print(y_pred)

"""4.5 Model Evaluation

Heading

Accuracy
"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

"""Precision"""

from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)

print("Precision :", precision)

"""Recall"""

from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)

print("Recall :", recall)

"""Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""4.6 Confusion Matrix

Heading

Create Matrix
"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

cm

"""Plot"""

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""4.7 Feature Importance

Heading

Calculate Importance
"""

importance = pd.DataFrame(
    {
        "Feature": X.columns,
        "Importance": rf_model.feature_importances_
    }
)

importance

"""Sort"""

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance

"""Plot"""

plt.figure(figsize=(8,5))

sns.barplot(
    data=importance,
    x="Importance",
    y="Feature"
)

plt.title("Feature Importance")

plt.show()

"""4.8 Save the Model

Heading

Save
"""

import joblib

joblib.dump(rf_model, "model.pkl")

"""Load Model (Optional Check)"""

loaded_model = joblib.load("model.pkl")

"""Import Libraries"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

""" Page Title"""

st.title("🎬 MovieIQ")
st.subheader("Movie Success Prediction Dashboard")

"""Load Dataset"""

df = pd.read_csv("movies.csv")

"""Load Machine Learning Model"""

model = joblib.load("model.pkl")

"""STAGE 5 : Streamlit

Import Libraries
"""

import streamlit as st

"""Page Title"""

st.title("🎬 MovieIQ")
st.subheader("Movie Success Prediction")

"""Load Dataset"""

df = pd.read_csv("movies.csv")

"""Load Model"""

model = joblib.load("model.pkl")

"""Sidebar Filters"""

st.sidebar.header("Filter Movies")

genre = st.sidebar.selectbox(
    "Select Genre",
    sorted(df["genres"].unique())
)

vote = st.sidebar.slider(
    "Minimum Vote Average",
    0.0,
    10.0,
    5.0
)

"""Filter Dataset"""

filtered_df = df[
    (df["genres"] == genre) &
    (df["vote_average"] >= vote)
]

"""Show Dataset"""

st.header("Filtered Movies")

st.dataframe(filtered_df)

"""EDA Charts

Budget vs Revenue
"""

st.header("Budget vs Revenue")

fig, ax = plt.subplots(figsize=(8,5))

sns.scatterplot(
    data=filtered_df,
    x="budget",
    y="revenue",
    ax=ax
)

st.pyplot(fig)

"""Genre Distribution"""

st.header("Genre Distribution")

fig, ax = plt.subplots(figsize=(8,5))

filtered_df["genres"].value_counts().plot(
    kind="bar",
    ax=ax
)

st.pyplot(fig)

"""Correlation Heatmap"""

st.header("Correlation Heatmap")

fig, ax = plt.subplots(figsize=(8,6))

sns.heatmap(
    filtered_df.select_dtypes(include="number").corr(),
    annot=True,
    cmap="coolwarm",
    ax=ax
)

st.pyplot(fig)

"""Statistical Test Results

Since you already calculated the T-Test and Chi-Square in Jupyter, just display the results.
"""

st.header("Statistical Test Results")

st.write("T-Test Result")

st.write("P-value :", 0.001)

st.write("Result : Significant Difference")

st.write("-------------------------")

st.write("Chi-Square Test")

st.write("P-value :", 0.02)

st.write("Result : Genre is Associated with Success")

"""Movie Prediction

User Inputs
"""

st.header("Movie Success Prediction")

budget = st.number_input("Budget", min_value=0)

popularity = st.number_input("Popularity", min_value=0.0)

runtime = st.number_input("Runtime", min_value=0)

vote_average = st.number_input(
    "Vote Average",
    min_value=0.0,
    max_value=10.0
)

"""Prediction Button"""

if st.button("Predict"):

    prediction = model.predict(
        [[budget, popularity, runtime, vote_average]]
    )

    if prediction[0] == 1:
        st.success("✅ Movie will be Successful")
    else:
        st.error("❌ Movie may not be Successful")